{
 "title": "Kafka Overview",
 "description": "Overview of topic and broker activity",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "kafka cpu cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kafka-cluster\", container=\"kafka\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kafka-cluster\", container=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "produced messages per topic/node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesinpersec_count{topic!=\"__consumer_offsets\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consumed bytes per topic/node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesoutpersec_count{topic!=\"__consumer_offsets\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "offset messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesinpersec_count{topic=\"__consumer_offsets\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}