alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.localtest.me
grafana:
  ingress:
    enabled: true
    hosts: 
      - grafana.localtest.me

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.localtest.me
  prometheusSpec:
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    ruleNamespaceSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
