broker:
  resourcesPreset: large
  automountServiceAccountToken: true
controller:
  resourcesPreset: large
  automountServiceAccountToken: true
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
rbac:
  create: true
