apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-awesome
  namespace: argo-cd
spec:
  sourceRepos:
    - https://github.com/bittrance/*
  sourceNamespaces:
    - team-awesome
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-awesome
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/bittrance/kubernetes-experiments
    targetRevision: argocd-promotion
    path: argocd-promotion/team-awesome-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: team-awesome
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-awesome
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: ClusterScmProvider
metadata:
  name: bittrance-gitops-promoter
spec:
  github:
    appID: 1460251
    installationID: 72971609
  secretRef:
    name: bittrance-gitops-promoter
