apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-gateway-tls
spec:
  secretName: loki-gateway-tls
  isCA: false
  usages:
    - server auth
  dnsNames:
    - loki.localtest.me
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Secret
metadata:
  name: loki-gateway-tls
type: Opaque
