apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage
spec:
  secretName: backstage-certificate
  isCA: false
  usages:
    - server auth
  dnsNames:
    - backstage.localtest.me
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-certificate
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-entities
data:
  users.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: bittrance_gmail.com
    spec:
      profile:
        email: bittrance@gmail.com
      memberOf: [guests]
