apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage
spec:
  secretName: backstage-certificate
  isCA: false
  usages:
    - server auth
  dnsNames:
    - backstage.localtest.me
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-certificate
type: Opaque

