apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-certificate
spec:
  secretName: dex-certificate
  isCA: false
  usages:
    - server auth
  dnsNames:
    - dex.oidc-federation.test
    - dex
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-certificate
type: Opaque
