apiVersion: v1
kind: Namespace
metadata:
  name: tidb-cluster
---
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: hello-tidb
  namespace: tidb-cluster
spec:
  version: v8.5.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    # maxFailoverCount: 0
    replicas: 3
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    # maxFailoverCount: 0
    # evictLeaderTimeout: 1m
    replicas: 3
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: pingcap/tidb
    # maxFailoverCount: 0
    replicas: 3
    service:
      type: LoadBalancer
    config: {}
